### ISSUE TITLE
Update/remove bio python library

### ISSUE THREAD

**Issue by badgerben** [solislemuslab/bioklustering#5]
The version of bio referenced in requirements.txt is no longer available. See https://pypi.org/project/bio/#history.
```
bio~=0.2.3
```
A quick look through the code, I don't see the bio utility being used directly. I do see references to biopython, which happens to be a dependency for bio. So, possible that bio could be removed and biopython added to requirements.txt.

**Comment by crsl4** [comment]
Thanks Ben! We are indeed working on updating the requirements, so we should have a commit soon fixing this.

**Comment by crsl4** [comment]
@samozm @YukeWu

**Comment by crsl4** [comment]
Fixed with [commit](https://github.com/solislemuslab/bioklustering/commit/46468b57ae8f5d2ee44c0f8043e2abc660c067a9).
